from graphics import circle,rectangle #importing circle and rectangle function from graphics package
r=int(input("Enter the radius of circle:"))
circle.areac(r)
circle.peric(r)
l=int(input("\nEnter the length of rectangle:"))
b=int(input("Enter the breadth of rectangle:"))
rectangle.arear(l,b)
rectangle.perir(l,b)
from graphics.dgraphics import cuboid,sphere
l1=int(input("\nEnter the length of cuboid:"))
b1=int(input("Enter the breadth of cuboid:"))
h1=int(input("Enter the height of cuboid:"))
cuboid.areacub(l1,b1,h1)
cuboid.pericub(l1,b1,h1)
r1=int(input("\nEnter the radius of sphere:"))
sphere.areas(r1)
sphere.peris(r1)